spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: labuser
    password: labpass123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000

server:
  port: 8081

